name: prova_p2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  # O 'sdk' deve ter 2 espaços
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  # O 'flutter' deve ter 2 espaços
  flutter:
    sdk: flutter

  # Cada pacote deve ter 2 espaços
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.1
  intl: ^0.19.0

dev_dependencies:
  # O 'flutter_test' deve ter 2 espaços
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  # O 'uses-material-design' deve ter 2 espaços
  uses-material-design: true